// src/lib/anomaly-filter.ts
//
// The dashboard's "ATTENTION NEEDED" yellow box is generated by hardcoded
// client-side rules (e.g. "ROAS < 0.5 and spend > $100 → flag"). These rules
// don't know about user_notes or directives. This helper filters out anomalies
// that mention any metric the user has explicitly told us to ignore.
//
// Used by InsightChat to strip ROAS-related anomalies when the user has said
// things like "ignore ROAS" or "don't focus on ROAS" in their client profile.

// Metric keywords we know how to detect in anomaly strings.
// If a user-directive bans a metric, we suppress anomalies that mention it.
const METRIC_KEYWORDS: Record<string, string[]> = {
  roas: ['roas', 'return on ad spend', 'return on adspend'],
  cpa: ['cpa', 'cost per acquisition', 'cost per conversion', 'costperconv'],
  cpl: ['cpl', 'cost per lead'],
  ctr: ['ctr', 'click-through', 'clickthrough', 'click through'],
  cpc: ['cpc', 'cost per click'],
  cpm: ['cpm', 'cost per mille', 'cost per thousand'],
  conversions: ['conversion', 'converts'],
  spend: ['spend', 'budget'],
  impressions: ['impression'],
  clicks: ['click'],
  frequency: ['frequency', 'freq'],
  reach: ['reach'],
}

// Phrases in user_notes that indicate "ignore this metric"
const IGNORE_PATTERNS = [
  /\bignore\s+([a-z\s/]+)/i,
  /\bdon'?t\s+(?:focus\s+on|worry\s+about|mention|use|consider|track)\s+([a-z\s/]+)/i,
  /\bdo\s+not\s+(?:focus\s+on|worry\s+about|mention|use|consider|track)\s+([a-z\s/]+)/i,
  /\bnever\s+(?:focus\s+on|mention|use|consider)\s+([a-z\s/]+)/i,
  /\bstop\s+(?:focusing\s+on|mentioning|considering)\s+([a-z\s/]+)/i,
  /\bdeprioriti[sz]e\s+([a-z\s/]+)/i,
  /\bdisregard\s+([a-z\s/]+)/i,
  /\bset\s+aside\s+([a-z\s/]+)/i,
  /\bnot\s+a\s+(?:primary|key|main|focus)\s+([a-z]+)/i,
]

// Extract a set of metric keys the user has banned, given their user_notes text.
export function extractBannedMetrics(userNotes: string | null | undefined): Set<string> {
  const banned = new Set<string>()
  if (!userNotes) return banned

  const text = userNotes.toLowerCase()

  IGNORE_PATTERNS.forEach(re => {
    const matches = text.matchAll(new RegExp(re.source, 'gi'))
    for (const m of matches) {
      const phrase = (m[1] || '').toLowerCase()
      // Check which metrics this phrase mentions
      Object.entries(METRIC_KEYWORDS).forEach(([metric, keywords]) => {
        if (keywords.some(kw => phrase.includes(kw))) {
          banned.add(metric)
        }
      })
    }
  })

  // Also: scan the entire user_notes for "metric X is not important", etc.
  Object.entries(METRIC_KEYWORDS).forEach(([metric, keywords]) => {
    keywords.forEach(kw => {
      // Pattern: "[keyword] is not important / off the table / not a focus"
      const negativeRe = new RegExp(
        `\\b${kw}\\b[^.]{0,40}(?:not\\s+(?:important|primary|key|relevant|a\\s+focus)|off[\\s-]the[\\s-]table|deprioriti[sz]ed?)`,
        'i'
      )
      if (negativeRe.test(text)) banned.add(metric)
    })
  })

  return banned
}

// Filter an anomaly array, removing any that mention banned metrics.
export function filterAnomalies(
  anomalies: string[],
  userNotes: string | null | undefined
): string[] {
  const banned = extractBannedMetrics(userNotes)
  if (banned.size === 0) return anomalies

  return anomalies.filter(anomaly => {
    const lower = anomaly.toLowerCase()
    for (const metric of banned) {
      const keywords = METRIC_KEYWORDS[metric] || []
      if (keywords.some(kw => lower.includes(kw))) {
        return false // suppress this anomaly
      }
    }
    return true
  })
}
