// LORAMER_BREAKDOWN_REGISTRY_V1
//
// THE ONE DECLARED SOURCE for every (platform, breakdown_type, entity_level) tuple LoraMer captures in
// metrics_daily. In G2 STEP 2 both the Lora query layer (src/lib/metrics-query.ts — BREAKDOWN_PLATFORMS /
// BREAKDOWN_PRIMARY / SPEND_ZERO / LEVEL scoping) and the Lora tool schema (src/lib/claude-tools.ts —
// query_breakdown enums) will DERIVE from this file. Until STEP 2 wires them, this file is authored but NOT
// consumed by the read path, so creating it changes ZERO runtime behavior.
//
// WHY IT EXISTS (G2 — LORA SEES EVERYTHING): millions of captured rows were UNREADABLE by Lora because the
// allowlist in metrics-query.ts and the enum in claude-tools.ts were two hand-maintained lists that drifted
// from what the writers actually persist (2026-07-16 recon: 54 hard-blind tuples — the whole Google geo
// family, all 12 GA dimensional types, Meta age_gender). Collapsing both onto this single source kills the
// drift as a CLASS — the settleRevenue / META_BREADTH_FORWARD / resolveShellClient shape.
//
// GRANULARITY: one entry per (platform, breakdown_type) — NOT per breakdown_type — because entity levels
// differ BY platform for the same dimension (google device = campaign/ad_group/ad/keyword; meta device =
// account/campaign/ad_set/ad). A single platforms[]+entityLevels[] entry cannot express that asymmetry
// without over-declaring tuples that were never captured. Expanding all entries by entityLevels reproduces
// EXACTLY the 118 live tuples the recon found.
//
// GEO COLLAPSE (limit #1 — a ~44-value flat enum degrades tool selection): the 19 Google geo breakdown_types
// collapse to ONE tool-facing type 'geo' + a (geoGrain, geoScope) axis — EXCEPT geo_country / geo_region,
// which keep their own tool types so the SAME country/region question unifies Shopify + Meta + Google (the
// recon "add google to geo_country/geo_region platforms"). So 'geo' carries the 17 google-only fine grains;
// geo_country/geo_region carry country/region ACROSS all platforms. Every real geo breakdown_type maps to
// exactly ONE toolType — no tuple is declared twice.
//
// DERIVED-FROM-CODE GUARD: tests/guards/breakdown-registry-drift.guard.mjs asserts the query_breakdown enums
// in claude-tools.ts equal the enums derived from this file. THAT GUARD PROVES SCHEMA / QUERY-LAYER PARITY
// ONLY — it CANNOT prove live-DB reachability (CI has no DB, and the DB is prod). A separate non-build
// reachability check (loose-index-scan of live DISTINCT tuples vs this registry) is a G2 STEP 2 deliverable.

export type Platform = 'google' | 'meta' | 'shopify' | 'woocommerce' | 'ga'
export type EntityLevel = 'account' | 'campaign' | 'ad_group' | 'ad_set' | 'ad' | 'keyword' | 'product' | 'variant'
export type Surface = 'base' | 'breakdown'
export type RankBy = 'spend' | 'conversions' | 'revenue' | 'impressions' | 'clicks'
export type GeoScope = 'ad' | 'user'

export interface BreakdownEntry {
  platform: Platform
  breakdownType: string        // the REAL metrics_daily breakdown_type string ('' = base rows)
  toolType: string             // the tool-facing type Lora selects (geo family collapses to 'geo'); '' for base
  surface: Surface             // 'base' = read via query_metrics (level); 'breakdown' = read via query_breakdown
  entityLevels: EntityLevel[]  // the grains this (platform, breakdown_type) is actually captured at, per the live DB
  rankBy: RankBy               // default ranking anchor; SPEND_ZERO families rank by conversions, stores/ga by revenue
  additive: boolean            // false = non-additive per-entity projection (impression_share, video) — never summed
  highCardinality: boolean     // true = wide-window reads risk the 8s statement_timeout (limit #2); must have rankBy
  geoGrain?: string            // city|county|metro|state|province|district|postal|most_specific|region|country
  geoScope?: GeoScope          // ad-location vs user-location
  note?: string
}

// One entry per (platform, breakdown_type). Authored one-per-line so the hermetic guard can text-derive the
// declared enums without executing TypeScript. Expands to the 118 live tuples the 2026-07-16 recon verified.
export const REGISTRY: BreakdownEntry[] = [
  // ── BASE ROWS (breakdown_type ''): read via query_metrics `level`, NOT query_breakdown ────────────────────
  { platform: 'ga', breakdownType: '', toolType: '', surface: 'base', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'google', breakdownType: '', toolType: '', surface: 'base', entityLevels: ['account', 'campaign', 'ad_group', 'ad'], rankBy: 'spend', additive: true, highCardinality: false },
  { platform: 'meta', breakdownType: '', toolType: '', surface: 'base', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false },
  { platform: 'shopify', breakdownType: '', toolType: '', surface: 'base', entityLevels: ['account', 'product', 'variant'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'woocommerce', breakdownType: '', toolType: '', surface: 'base', entityLevels: ['account', 'product', 'variant'], rankBy: 'revenue', additive: true, highCardinality: false },

  // ── GA DIMENSIONAL (platform 'ga', account grain): the entire LORAMER_GA_DIMENSIONAL_CAPTURE_V1 flight ─────
  { platform: 'ga', breakdownType: 'ga_age', toolType: 'ga_age', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'ga', breakdownType: 'ga_campaign', toolType: 'ga_campaign', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'ga', breakdownType: 'ga_channel', toolType: 'ga_channel', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'ga', breakdownType: 'ga_device', toolType: 'ga_device', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'ga', breakdownType: 'ga_event', toolType: 'ga_event', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'ga', breakdownType: 'ga_gender', toolType: 'ga_gender', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'ga', breakdownType: 'ga_geo_city', toolType: 'ga_geo_city', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: true },
  { platform: 'ga', breakdownType: 'ga_geo_country', toolType: 'ga_geo_country', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'ga', breakdownType: 'ga_geo_region', toolType: 'ga_geo_region', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'ga', breakdownType: 'ga_item', toolType: 'ga_item', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },
  { platform: 'ga', breakdownType: 'ga_landing_page', toolType: 'ga_landing_page', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: true },
  { platform: 'ga', breakdownType: 'ga_source_medium', toolType: 'ga_source_medium', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false },

  // ── GOOGLE non-geo dimensional (already visible today, preserved) ─────────────────────────────────────────
  { platform: 'google', breakdownType: 'conversion_action', toolType: 'conversion_action', surface: 'breakdown', entityLevels: ['campaign', 'ad_group', 'keyword'], rankBy: 'conversions', additive: true, highCardinality: false, note: 'SPEND_ZERO — per-action conversions, spend cols are 0; rank by conversions. Grain-complete campaign+ad_group+keyword (G-FILL#9, LORAMER_GOOGLE_CONV_ACTION_DEEP_V1).' },
  { platform: 'google', breakdownType: 'device', toolType: 'device', surface: 'breakdown', entityLevels: ['campaign', 'ad_group', 'ad', 'keyword'], rankBy: 'spend', additive: true, highCardinality: false, note: 'ad_group + keyword grains are new to Lora (were unreachable — entityLevel enum lacked them).' },
  { platform: 'google', breakdownType: 'hour', toolType: 'hour', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, note: 'hour "00" is a Google catch-all bucket (Display/PMax full-day spend) — not real midnight.' },
  { platform: 'google', breakdownType: 'impression_share', toolType: 'impression_share', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: false, highCardinality: false, note: 'NON-ADDITIVE point-in-time ratios — never summed; most-recent in-window per entity. Grain-complete campaign+ad_group (G-FILL#9, LORAMER_GOOGLE_IS_DEEP_V1); NOT served at keyword.' },
  { platform: 'google', breakdownType: 'keyword', toolType: 'keyword', surface: 'breakdown', entityLevels: ['ad_group'], rankBy: 'spend', additive: true, highCardinality: false },
  { platform: 'google', breakdownType: 'search_term', toolType: 'search_term', surface: 'breakdown', entityLevels: ['ad_group'], rankBy: 'spend', additive: true, highCardinality: false, note: 'wide-window reads page all rows to JS — the 12mo≈18s ROUTE finding; STEP 2 must SQL-aggregate.' },
  // Google age/gender (G-FILL#3) — SAME cross-platform toolType as Meta age/gender (query requires platform now).
  // age_range_view/gender_view served at campaign + ad_group only; value = the raw enum (AGE_RANGE_* / MALE/FEMALE/UNDETERMINED).
  { platform: 'google', breakdownType: 'age', toolType: 'age', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, note: 'google age (age_range_view); value = AGE_RANGE_* enum. FLAG-NOT-BLOCK partition of campaign spend.' },
  { platform: 'google', breakdownType: 'gender', toolType: 'gender', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, note: 'google gender (gender_view); value = MALE/FEMALE/UNDETERMINED. FLAG-NOT-BLOCK partition of campaign spend.' },

  // ── GOOGLE GEO FAMILY — 19 real types, collapsed to toolType 'geo' EXCEPT geo_country/geo_region ──────────
  // ad-location scope (segments.geo_target_*)
  { platform: 'google', breakdownType: 'geo_city', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: true, geoGrain: 'city', geoScope: 'ad' },
  { platform: 'google', breakdownType: 'geo_country', toolType: 'geo_country', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'country', geoScope: 'ad' },
  { platform: 'google', breakdownType: 'geo_county', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'county', geoScope: 'ad' },
  { platform: 'google', breakdownType: 'geo_district', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'district', geoScope: 'ad' },
  { platform: 'google', breakdownType: 'geo_metro', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'metro', geoScope: 'ad' },
  { platform: 'google', breakdownType: 'geo_most_specific', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: true, geoGrain: 'most_specific', geoScope: 'ad' },
  { platform: 'google', breakdownType: 'geo_postal', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: true, geoGrain: 'postal', geoScope: 'ad' },
  { platform: 'google', breakdownType: 'geo_province', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'province', geoScope: 'ad' },
  { platform: 'google', breakdownType: 'geo_region', toolType: 'geo_region', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'region', geoScope: 'ad' },
  { platform: 'google', breakdownType: 'geo_state', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'state', geoScope: 'ad' },
  // user-location scope (segments.geo_target_* user)
  { platform: 'google', breakdownType: 'user_geo_city', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: true, geoGrain: 'city', geoScope: 'user' },
  { platform: 'google', breakdownType: 'user_geo_county', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'county', geoScope: 'user' },
  { platform: 'google', breakdownType: 'user_geo_district', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'district', geoScope: 'user' },
  { platform: 'google', breakdownType: 'user_geo_metro', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'metro', geoScope: 'user' },
  { platform: 'google', breakdownType: 'user_geo_most_specific', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: true, geoGrain: 'most_specific', geoScope: 'user' },
  { platform: 'google', breakdownType: 'user_geo_postal', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: true, geoGrain: 'postal', geoScope: 'user' },
  { platform: 'google', breakdownType: 'user_geo_province', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'province', geoScope: 'user' },
  { platform: 'google', breakdownType: 'user_geo_region', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'region', geoScope: 'user' },
  { platform: 'google', breakdownType: 'user_geo_state', toolType: 'geo', surface: 'breakdown', entityLevels: ['campaign', 'ad_group'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'state', geoScope: 'user' },

  // ── META dimensional ──────────────────────────────────────────────────────────────────────────────────────
  { platform: 'meta', breakdownType: 'action_type', toolType: 'action_type', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'conversions', additive: true, highCardinality: false, note: 'SPEND_ZERO — per-action conversions; rank by conversions.' },
  { platform: 'meta', breakdownType: 'age', toolType: 'age', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false },
  { platform: 'meta', breakdownType: 'age_gender', toolType: 'age_gender', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, note: 'hard-blind at HEAD — never in the enum despite 425,293 captured rows.' },
  { platform: 'meta', breakdownType: 'device', toolType: 'device', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false },
  { platform: 'meta', breakdownType: 'device_platform', toolType: 'device_platform', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false },
  { platform: 'meta', breakdownType: 'gender', toolType: 'gender', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false },
  { platform: 'meta', breakdownType: 'geo_country', toolType: 'geo_country', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'country', geoScope: 'user' },
  { platform: 'meta', breakdownType: 'geo_region', toolType: 'geo_region', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, geoGrain: 'region', geoScope: 'user' },
  { platform: 'meta', breakdownType: 'hour', toolType: 'hour', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false },
  { platform: 'meta', breakdownType: 'placement', toolType: 'placement', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, note: 'writer stores publisher:position as breakdown_type=placement; legacy read-name publisher_platform aliases here. Grain-complete campaign+ad_set+ad (LORAMER_META_PLACEMENT_ADSET_AD_V1); account is derive-not-capture (clean rollup of campaign).' },
  { platform: 'meta', breakdownType: 'video', toolType: 'video', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: false, highCardinality: false, note: 'NON-ADDITIVE per-entity projection — view counts summed, rates null across multi-day windows.' },

  // ── META creative-ASSET family (M-FILL#1) — 7 breakdown_types, campaign/ad_set/ad ONLY (account served-empty). ─
  // WRITE-ONLY component attribution: per-asset spend is NOT a partition — NEVER sum across asset types or to the ad
  // total (title over-counts under Dynamic Creative). breakdown_value = the canonical label per type (description=id).
  { platform: 'meta', breakdownType: 'image_asset', toolType: 'image_asset', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, note: 'creative image; value = image name. Component attribution — never sum across asset types or to the ad total.' },
  { platform: 'meta', breakdownType: 'video_asset', toolType: 'video_asset', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, note: 'creative video; value = video name. Component attribution — never sum across asset types or to the ad total.' },
  { platform: 'meta', breakdownType: 'title_asset', toolType: 'title_asset', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, note: 'headline text; value = the headline. Component attribution — never sum across asset types or to the ad total.' },
  { platform: 'meta', breakdownType: 'body_asset', toolType: 'body_asset', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, note: 'primary text; value = the body (capped). Component attribution — never sum across asset types or to the ad total.' },
  { platform: 'meta', breakdownType: 'call_to_action_asset', toolType: 'call_to_action_asset', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, note: 'CTA enum (LEARN_MORE…). Component attribution — never sum across asset types or to the ad total.' },
  { platform: 'meta', breakdownType: 'description_asset', toolType: 'description_asset', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, note: 'link description; value = ASSET ID ONLY (Meta serves no label). Component attribution — never sum across asset types or to the ad total.' },
  { platform: 'meta', breakdownType: 'link_url_asset', toolType: 'link_url_asset', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: false, note: 'destination URL; value = website_url (else asset id). Component attribution — never sum across asset types or to the ad total.' },

  // ── META attribution windows (M-FILL#2) — per (action_type × window) conversions/value; spend 0 (SPEND_ZERO). ──
  { platform: 'meta', breakdownType: 'ad_format_asset', toolType: 'ad_format_asset', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: false, highCardinality: false, note: 'Ad FORMAT asset. Value is an ID with no label served (same shape as description_asset). Probed live 2026-07-19: returns rows on both probe clients. WRITE-ONLY, NON-ADDITIVE — component attribution like every other Meta asset breakdown: it does NOT partition spend, so never sum across values or up to the ad/campaign total. account grain is served-empty → 3 grains IS complete. Individual-asset only: per-COMBINATION asset attribution is IMPOSSIBLE via Insights (joint asset breakdowns return #100) and this does NOT move toward it (LORAMER_META_BATCH_MB_V1, M-FILL#1b).' },
  { platform: 'meta', breakdownType: 'creative_relaxation_asset_type', toolType: 'creative_relaxation_asset_type', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: false, highCardinality: false, note: 'Advantage+ creative-relaxation asset type (e.g. "original"). Probed 2026-07-19: populated on Glass Plus, empty on 2024 data (feature postdates it). WRITE-ONLY, NON-ADDITIVE — component attribution like every other Meta asset breakdown: it does NOT partition spend, so never sum across values or up to the ad/campaign total. account grain is served-empty → 3 grains IS complete. Individual-asset only: per-COMBINATION asset attribution is IMPOSSIBLE via Insights (joint asset breakdowns return #100) and this does NOT move toward it (LORAMER_META_BATCH_MB_V1, M-FILL#1b).' },
  { platform: 'meta', breakdownType: 'flexible_format_asset_type', toolType: 'flexible_format_asset_type', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: false, highCardinality: false, note: 'Flexible-format asset type (e.g. "unknown"). Probed 2026-07-19: populated on Glass Plus, empty on 2024 data. WRITE-ONLY, NON-ADDITIVE — component attribution like every other Meta asset breakdown: it does NOT partition spend, so never sum across values or up to the ad/campaign total. account grain is served-empty → 3 grains IS complete. Individual-asset only: per-COMBINATION asset attribution is IMPOSSIBLE via Insights (joint asset breakdowns return #100) and this does NOT move toward it (LORAMER_META_BATCH_MB_V1, M-FILL#1b).' },
  { platform: 'meta', breakdownType: 'gen_ai_asset_type', toolType: 'gen_ai_asset_type', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: false, highCardinality: false, note: 'Generative-AI asset type (e.g. "original") — the AI-creative axis. Probed 2026-07-19: populated on Glass Plus, empty on 2024 data. WRITE-ONLY, NON-ADDITIVE — component attribution like every other Meta asset breakdown: it does NOT partition spend, so never sum across values or up to the ad/campaign total. account grain is served-empty → 3 grains IS complete. Individual-asset only: per-COMBINATION asset attribution is IMPOSSIBLE via Insights (joint asset breakdowns return #100) and this does NOT move toward it (LORAMER_META_BATCH_MB_V1, M-FILL#1b).' },
  { platform: 'meta', breakdownType: 'product_id', toolType: 'product_id', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: false, highCardinality: true, note: 'Catalog / Advantage+ product grain. WRITE-ONLY, NON-ADDITIVE — MEASURED 2026-07-19: the breakdown carries $7,128.70 against $13,889.16 on the very campaigns it appears in (49% shortfall), so it does NOT partition even WITHIN catalog campaigns and is never reconciled. EMPTY means the account runs no catalog/Advantage+ campaigns — NOT a capture failure. account grain is derive-not-capture → 3 grains complete. HIGH CARDINALITY (one value per SKU) — always rank/limit (LORAMER_META_BATCH_MG_V1).' },
  { platform: 'meta', breakdownType: 'comscore_market', toolType: 'comscore_market', surface: 'breakdown', entityLevels: ['campaign', 'ad_set', 'ad'], rankBy: 'spend', additive: true, highCardinality: true, note: 'Market/DMA grain — the FORWARD-ONLY replacement for `dma`, which Meta REMOVED API-wide (historical DMA data is permanently unrecoverable: a platform purge, not our gap). Populates ONLY for comScore-MEASURED accounts and only from ~2026-06. ⚠ AN EMPTY OR $0 comscore_market BREAKDOWN MEANS THE ACCOUNT IS NOT COMSCORE-MEASURED — it does NOT mean no delivery and it is NOT a data gap; never report thin coverage here as missing data. Near-partitions the campaigns it covers → FLAG-NOT-BLOCK on spend. account grain derive-not-capture → 3 grains complete (LORAMER_META_BATCH_MG_V1).' },
  { platform: 'meta', breakdownType: 'attribution_window', toolType: 'attribution_window', surface: 'breakdown', entityLevels: ['account', 'campaign', 'ad_set', 'ad'], rankBy: 'conversions', additive: true, highCardinality: false, note: 'value = "<action_type>:<window>" (1d_click/7d_click/28d_click/1d_view). Windows OVERLAP (1d⊂7d⊂28d) + view/click double-count → NEVER sum across windows.' },

  // ── SHOPIFY dimensional (store ship-to geo) ──────────────────────────────────────────────────────────────
  { platform: 'shopify', breakdownType: 'geo_country', toolType: 'geo_country', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, geoGrain: 'country', geoScope: 'ad' },
  { platform: 'shopify', breakdownType: 'geo_region', toolType: 'geo_region', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, geoGrain: 'region', geoScope: 'ad' },
  { platform: 'shopify', breakdownType: 'abandoned_checkout', toolType: 'abandoned_checkout', surface: 'breakdown', entityLevels: ['account'], rankBy: 'conversions', additive: false, highCardinality: false, note: 'WRITE-ONLY POTENTIAL/LOST revenue — Σ abandoned-checkout totalPriceSet in conversionValue + abandoned count in conversions; spend/revenue are 0. NEVER actual revenue; never sum/reconcile into net sales or order counts. ~90-day Shopify retention floor → forward-first, NOT full history like orders (S-FILL#2, LORAMER_SHOPIFY_ABANDONED_VALUE_V1).' },
  { platform: 'shopify', breakdownType: 'discount_code', toolType: 'discount_code', surface: 'breakdown', entityLevels: ['account'], rankBy: 'conversions', additive: false, highCardinality: false, note: 'WRITE-ONLY per-code applied discount — Σ line-item allocations for the code in conversionValue + orders-using-code in conversions; spend/revenue are 0. A SUBSET of total discounting (excludes manual/automatic NON-code discounts) — NEVER sum/reconcile into net sales OR the order discount total (a code allocation can exceed an order current discount total). breakdown_value = code string; multiple codes per order allowed (S-FILL#3, LORAMER_SHOPIFY_DISCOUNT_CODE_V1).' },
  { platform: 'shopify', breakdownType: 'product_collection', toolType: 'product_collection', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: false, highCardinality: true, note: 'Collection membership, from a SEPARATE id-batched call — NEVER the orders query, which Shopify hard-rejects at 1,036 points (MAX_COST_EXCEEDED, measured 2026-07-19). NON-ADDITIVE: a product belongs to MANY collections, so its full net is counted under each and the sum EXCEEDS net sales — same over-count shape as product_tag. Compare collections to EACH OTHER; never sum, never reconcile to net sales. CAPTURE-TIME SNAPSHOT: membership is mutable and NOT reconstructable historically, so a re-walk records today membership against old orders. Products whose collections could not be fetched emit NO row (never a fabricated bucket) (LORAMER_SHOPIFY_BATCH_B_V1).' },
  { platform: 'shopify', breakdownType: 'customer_cohort', toolType: 'customer_cohort', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, note: 'Customer cohort by LIFETIME order count, bucketed 1 / 2-3 / 4-9 / 10+ (UNKNOWN = guest checkout or no linked customer, kept IN the partition). PARTITIONS the day net — each order maps to exactly one bucket via its customer — so the sum equals account net; reconciles FLAG-NOT-BLOCK. revenue/conversions on the row ARE windowed. extra.avgLifetimeSpent is a LIFETIME figure and is NOT summable across days (a customer ordering on ten days would contribute their whole lifetime value ten times) — labelled ltvSemantics=LIFETIME_NOT_WINDOWED and caveated to Lora in metrics-query.ts. Non-PII: buckets and counts only, never a per-customer row (LORAMER_SHOPIFY_BATCH_C_V1).' },
  { platform: 'shopify', breakdownType: 'financial_status', toolType: 'financial_status', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, note: 'Order FINANCIAL status (PAID/PENDING/REFUNDED/...). PARTITIONS the day net — one status per order — so the sum equals account net and it reconciles FLAG-NOT-BLOCK. CAPTURE-TIME SNAPSHOT, NOT AN ORDER-DATE FACT: status is MUTABLE, so a row records what was true WHEN THE DAY WAS CAPTURED and a re-walk can return different values. Older history is systematically MORE SETTLED than recent days, so a rising paid-share toward the past is a capture-timing ARTIFACT, never a trend. Caveat surfaced to Lora at query time in metrics-query.ts (LORAMER_SHOPIFY_BATCH_A3_V1).' },
  { platform: 'shopify', breakdownType: 'fulfillment_status', toolType: 'fulfillment_status', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, note: 'Order FULFILLMENT status (FULFILLED/UNFULFILLED/PARTIALLY_FULFILLED/...). PARTITIONS the day net; same posture and the SAME CAPTURE-TIME SNAPSHOT semantics as financial_status — mutable, re-walk-unstable, older history more settled. Caveat surfaced to Lora in metrics-query.ts (LORAMER_SHOPIFY_BATCH_A3_V1).' },
  { platform: 'shopify', breakdownType: 'product_type', toolType: 'product_type', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, note: 'Product TYPE grouping. Revenue projected onto the attribute from the SAME per-line net the product grain uses (order-level residual allocated pro-rata), so it PARTITIONS the day net — one type per product — and Σ product_type ≡ account net. Missing/blank productType buckets UNKNOWN, never dropped (LORAMER_SHOPIFY_BATCH_A2_V1).' },
  { platform: 'shopify', breakdownType: 'product_vendor', toolType: 'product_vendor', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, note: 'Product VENDOR grouping. Same per-line net basis as product_type; PARTITIONS the day net (one vendor per product), Σ ≡ account net. Blank vendor buckets UNKNOWN (LORAMER_SHOPIFY_BATCH_A2_V1).' },
  { platform: 'shopify', breakdownType: 'product_tag', toolType: 'product_tag', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: false, highCardinality: true, note: 'Product TAG grouping. NON-ADDITIVE BY CONSTRUCTION: a product carries MANY tags, so its full net is added to EVERY tag it holds and Σ product_tag EXCEEDS the day net by the average tags-per-product multiple. A row answers "how much revenue touched this tag", NEVER "what share of the day was this tag" — never sum across values, never reconcile to net sales. Untagged products bucket UNTAGGED. HIGH CARDINALITY (free-form merchant strings) — always rank/limit (LORAMER_SHOPIFY_BATCH_A2_V1).' },
  { platform: 'shopify', breakdownType: 'geo_city', toolType: 'geo_city', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: true, geoGrain: 'city', geoScope: 'ad', note: 'Ship-to CITY, third rung of the store geo ladder. breakdown_value = composite "<country>-<province>-<city>" (matches geo_region convention); missing city → "<cc>-<prov>-UNKNOWN", never dropped. PARTITIONS the day net (one shipping address per order) on the SAME currentSubtotalPriceSet basis as geo_country/geo_region. HIGH CARDINALITY — always rank/limit (S-FILL, LORAMER_SHOPIFY_BATCH_A1_V1).' },
  { platform: 'shopify', breakdownType: 'sales_channel', toolType: 'sales_channel', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, note: 'Order attribution — which channel the order came through (online store / POS / Meta / Google / draft). breakdown_value = channelInformation.channelDefinition.handle (canonical); channelName in extra. PARTITIONS the day net — exactly one channel per order, so Σ sales_channel ≡ account net; reconciles FLAG-NOT-BLOCK vs the account anchor like geo. Orders with no channelInformation bucket UNKNOWN rather than dropping out of the partition (S-FILL#1, LORAMER_SHOPIFY_BATCH_A1_V1).' },
  { platform: 'shopify', breakdownType: 'discount_type', toolType: 'discount_type', surface: 'breakdown', entityLevels: ['account'], rankBy: 'conversions', additive: false, highCardinality: false, note: 'The TYPE axis of discounting (code / manual / automatic / script), sibling to discount_code per-CODE. Σ line-item allocations per application subtype in conversionValue + orders-using-that-type in conversions (counted ONCE per order per type); spend/revenue are 0. WRITE-ONLY, NON-ADDITIVE: allocations OVERLAP and are a SUBSET of total discounting — a single allocation can exceed an order current discount total. NEVER sum/reconcile into net sales or the order discount total (LORAMER_SHOPIFY_BATCH_A1_V1).' },
  { platform: 'shopify', breakdownType: 'order_time', toolType: 'order_time', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: true, note: 'ORDER TIME-OF-DAY, RAW. One row PER ORDER; breakdown_value = the verbatim Shopify UTC ISO-8601 timestamp to the SECOND (e.g. 2024-11-29T14:03:27Z), entity_id = the order id so same-second orders cannot collide. NEVER bucketed at write time — bucket at READ time against the CLIENT timezone (a US merchant reading raw UTC hours is off by 4-7h). ADDITIVE: revenue is order NET on the same currentSubtotalPriceSet basis as the account row, so Σ order_time ≡ account net for the day. HIGH CARDINALITY (one row per order) — always rank/limit (S-FILL#7, LORAMER_SHOPIFY_ORDER_TIME_V1).' },
  // ── WOOCOMMERCE BREADTH (LORAMER_WOO_BATCH_WA_V1) — nine families, ALL read off the order JSON already ──
  // fetched (zero new vendor requests) and ALL emitted from the ONE shared row builder, so forward, catchup
  // and backfill carry them identically. Woo's net basis differs from Shopify's (INCLUDES shipping + tax,
  // refund-netted) and its geo basis is the BILLING address, not ship-to — both stated per-entry so no reader
  // ever treats a Woo family and its Shopify namesake as like-for-like.
  { platform: 'woocommerce', breakdownType: 'geo_country', toolType: 'geo_country', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, geoGrain: 'country', geoScope: 'user', note: 'BILLING-address country (ISO code) — billing, NOT ship-to: Woo shipping is legitimately empty for digital/virtual/local-pickup orders, so a ship-to basis would dump those into UNKNOWN for no reason. PARTITIONS the day net (one billing address per order) on the wooNetOf basis — o.total INCL shipping+tax, refund-netted, the SAME basis as the account row — so Σ geo_country ≡ account net and it reconciles FLAG-NOT-BLOCK. Orders with no billing country bucket UNKNOWN and STAY IN the partition (dropping them would shrink a total that must reconcile). NOTE the basis differs from shopify geo_country (net EXCLUDES shipping/tax, ship-to address) — never compare the two as like-for-like (LORAMER_WOO_BATCH_WA_V1).' },
  { platform: 'woocommerce', breakdownType: 'geo_region', toolType: 'geo_region', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, geoGrain: 'region', geoScope: 'user', note: 'BILLING-address state/province, second rung of the Woo geo ladder. breakdown_value = composite "<country>-<state>" (matches the Shopify geo convention so all three rungs read as one hierarchy); missing state → "<cc>-UNKNOWN", never dropped. PARTITIONS the day net on the wooNetOf basis, reconciles FLAG-NOT-BLOCK (LORAMER_WOO_BATCH_WA_V1).' },
  { platform: 'woocommerce', breakdownType: 'geo_city', toolType: 'geo_city', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: true, geoGrain: 'city', geoScope: 'user', note: 'BILLING-address city, third rung of the Woo geo ladder. breakdown_value = composite "<country>-<state>-<city>" — a BARE city name is unusable (Springfield exists in 30+ US states), so the value is always disambiguated. PARTITIONS the day net on the wooNetOf basis. HIGH CARDINALITY — always rank/limit. PII: country/state/city only; postcode, street address, email, phone and name are deliberately NEVER captured (LORAMER_WOO_BATCH_WA_V1).' },
  { platform: 'woocommerce', breakdownType: 'payment_method', toolType: 'payment_method', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, note: 'Payment gateway per order. PARTITIONS the day net — exactly one gateway per order — so Σ payment_method ≡ account net and it reconciles FLAG-NOT-BLOCK. breakdown_value = payment_method_title (the human name the merchant sees); the STABLE gateway slug rides extra.paymentMethodSlug because the title is merchant-EDITABLE free text and drifts across a rename — join on the slug, display the title. Orders with neither bucket UNKNOWN and stay in the partition (LORAMER_WOO_BATCH_WA_V1).' },
  { platform: 'woocommerce', breakdownType: 'order_status', toolType: 'order_status', surface: 'breakdown', entityLevels: ['account'], rankBy: 'conversions', additive: false, highCardinality: false, note: 'ALL WooCommerce order statuses incl. failed / cancelled / pending / on-hold — orders we already fetch (status=any) and previously DISCARDED entirely, so this is demand that was recorded nowhere. WRITE-ONLY, NON-ADDITIVE, and the reason is precise: the sale subset {completed, processing, refunded} partitions account net EXACTLY, but this family is ALL statuses, which is a SUPERSET of the anchor — and the reconcile-posture law tests whether a grain PARTITIONS the anchor, which a superset does not. So it never reconciles and is never summed to net. extra.isSale marks the subset that DOES tie: Σ(rows where isSale=true) ≡ account net by construction. ONE money basis throughout (wooNetOf on every order regardless of status) so nothing mixed lands in a summable column (LORAMER_WOO_BATCH_WA_V1).' },
  { platform: 'woocommerce', breakdownType: 'shipping_method', toolType: 'shipping_method', surface: 'breakdown', entityLevels: ['account'], rankBy: 'conversions', additive: false, highCardinality: false, note: 'Shipping method used, with the SHIPPING CHARGE (Σ shipping_lines.total) in conversionValue and orders-using-the-method in conversions; spend and revenue are FORCED 0. WRITE-ONLY, NON-ADDITIVE: shipping_lines is an ARRAY, so a split shipment puts ONE order under SEVERAL methods — attributing order net would double-count it, and the order count itself over-counts against total orders for the same reason (each order is counted once PER METHOD). The stable method_id slug rides extra alongside the merchant-editable title. NEVER sum into net sales or total orders (LORAMER_WOO_BATCH_WA_V1).' },
  { platform: 'woocommerce', breakdownType: 'coupon_code', toolType: 'coupon_code', surface: 'breakdown', entityLevels: ['account'], rankBy: 'conversions', additive: false, highCardinality: true, note: 'Per-coupon-code applied discount from order.coupon_lines — money in conversionValue, orders carrying the code in conversions, spend/revenue 0. WRITE-ONLY, NON-ADDITIVE: a coupon discount is discount MONEY, not a share of net sales, and orders with no coupon are absent entirely — a SUBSET, not a partition (the same posture Shopify discount_code carries, reached independently from the same law). No coupon on an order → NO row; there is deliberately no UNKNOWN bucket, because absence of a coupon is not a value. HIGH CARDINALITY — per-customer generated codes are a standard Woo plugin pattern. NOT from /reports/coupons/totals: that endpoint takes no date parameter, breaks down by discount TYPE not CODE, counts coupon DEFINITIONS not redemptions, and is cached for a year (LORAMER_WOO_BATCH_WA_V1).' },
  { platform: 'woocommerce', breakdownType: 'coupon_type', toolType: 'coupon_type', surface: 'breakdown', entityLevels: ['account'], rankBy: 'conversions', additive: false, highCardinality: false, note: 'The TYPE axis of the same money coupon_code carries per CODE. NOT A FIXED THREE-VALUE ENUM — that assumption was FALSIFIED at Gate-A: WooCommerce core ships percent / fixed_cart / fixed_product, but wc_get_coupon_types() is a PLUGIN-EXTENSIBLE filter and a real store returned "wbte_sc_bogo" (a BOGO plugin type) alongside core "fixed_cart". Treat the value set as open; a type you do not recognise is a plugin\'s, not a bug. UNKNOWN = an older WooCommerce that omits coupon_lines.discount_type, labelled rather than guessed. ALSO MEASURED: a BOGO-style coupon reports discount 0.00 because the benefit is a free PRODUCT, not money off — a $0 row is a real coupon use, never a missing value. Money in conversionValue, orders counted ONCE per order per type, spend/revenue 0. WRITE-ONLY, NON-ADDITIVE for the same reason as coupon_code (LORAMER_WOO_BATCH_WA_V1).' },
  { platform: 'woocommerce', breakdownType: 'order_time', toolType: 'order_time', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: true, note: 'ORDER TIME-OF-DAY, RAW. One row PER ORDER; entity_id = the order id so same-second orders cannot collide on the 7-col key. NEVER bucketed at write time — bucket at READ time against the CLIENT timezone. WOO-SPECIFIC vs the Shopify family: Shopify createdAt carries its offset, Woo date_created does NOT (site-local against an offset the payload never states), so breakdown_value is date_created_gmt with Z appended when Woo omits it — an unambiguous UTC instant — and BOTH verbatim vendor strings ride extra (createdAtGmtRaw, createdAtSiteLocalRaw). extra.tzBasis says which: a store returning no GMT field is labelled SITE_LOCAL and must NOT be read as UTC. THE ROW DATE IS THE SITE-LOCAL CAPTURE DAY, unchanged by this family — a late-evening local order can carry a UTC stamp on the NEXT calendar day, which is correct. ADDITIVE: revenue is order net on the account wooNetOf basis, so Σ order_time ≡ account net for the day. HIGH CARDINALITY (one row per order) — always rank/limit (LORAMER_WOO_BATCH_WA_V1).' },
  { platform: 'woocommerce', breakdownType: 'product_category', toolType: 'product_category', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: false, highCardinality: true, note: 'Product CATEGORY, the ONE Woo family sourced from a SECOND endpoint — line_items carry no category (confirmed on a real payload), so it comes from GET /wc/v3/products?include=<ids>&_fields=id,categories,tags, id-batched at <=100 and routed through the backfill counted+throttled fetch (never a raw fetch: that is the 2026-06-16 Shelley over-request incident). Net rides the SAME per-line pro-rata basis as the product grain, so a category figure is comparable to a product figure. NON-ADDITIVE BY CONSTRUCTION: a product belongs to MANY categories (MEASURED up to 11 on ONE Shelley product), so its full net is counted under EVERY category it sits in and Σ product_category EXCEEDS the day net — MEASURED 4.43× on a real 11-day window. A row answers "how much revenue touched this category", NEVER "what share of the day was this category". CAPTURE-TIME SNAPSHOT: the vendor exposes today\'s categorisation, not the categorisation as of the order date, so re-walking old days records how products are organised NOW (extra.semantics=CAPTURE_TIME_SNAPSHOT, extra.captured_at stamps when we asked). Products whose lookup failed emit NO row rather than a fabricated bucket (LORAMER_WOO_BATCH_WB_V1).' },
  { platform: 'woocommerce', breakdownType: 'product_tag', toolType: 'product_tag', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: false, highCardinality: true, note: 'Product TAG, from the SAME batched /wc/v3/products call as product_category (one request serves both — tags cost nothing extra). Same per-line pro-rata net basis, same NON-ADDITIVE over-count (many tags per product), same CAPTURE-TIME SNAPSHOT semantics. POPULATION REALITY, measured 2026-07-19: 0 of 71 products on the probe store carry ANY tag while 70 of 71 carry a category — Woo tags are optional and this merchant does not use them. An EMPTY product_tag family therefore means "this store does not tag its products", NOT a capture gap; do not report it as missing data. The family is real and populates for tag-using stores (LORAMER_WOO_BATCH_WB_V1).' },
  { platform: 'woocommerce', breakdownType: 'customer_cohort', toolType: 'customer_cohort', surface: 'breakdown', entityLevels: ['account'], rankBy: 'revenue', additive: true, highCardinality: false, note: 'Customer cohort by TRUE LIFETIME sale-order count, bucketed 1 / 2-3 / 4-9 / 10+ (Shopify COHORT_OF verbatim). IDENTITY IS THE EMAIL, NOT customer_id: WooCommerce sets customer_id=0 for GUEST checkout and guests are the MAJORITY on a real store (measured 86% of orders on a historic window), so a registered-only cohort would have been 86% UNKNOWN and useless; email is present on effectively every order (measured 100/100) and is how Triple Whale matches customers too. MEASURED RESULT: UNKNOWN came out at 0.00% of orders on the real store. PII POSTURE: identity is sha256(trim(lowercase(email))) computed IN MEMORY during the pass and DISCARDED when it returns — no email, no hash, no name, no address is ever written, and nested field trimming means the sweep does not even RECEIVE the rest of the customer record. UNKNOWN = the order carried no usable email; it STAYS IN the partition. PARTITIONS the day net on the wooNetOf basis (Gate-A: $0.00 residual against the same order state); reconciles FLAG-NOT-BLOCK. LIFETIME IS TRUE LIFETIME, not within-window — computed from a ONE-SHOT FULL-HISTORY sweep (woo-cohort-backfill.ts), which is why this family has its OWN drain step instead of riding the chunked breadth lap: a 21-day chunk cannot answer a lifetime question. STORE-SIZE CEILING 20,000 orders / 400s — above it the family emits NOTHING for that store (loud log, cursor left incomplete) rather than a partial sweep that would under-count lifetimes and mislabel loyal customers as first-timers (LORAMER_WOO_COHORT_V1).' },
]

// ── DERIVATIONS — the single source the tool schema (STEP 2) and this file's guard both read ─────────────────
const BREAKDOWN = REGISTRY.filter((e) => e.surface === 'breakdown')
const uniqSorted = (xs: string[]): string[] => [...new Set(xs)].sort()

/** The query_breakdown `breakdownType` enum: unique tool-facing types (geo family collapsed to 'geo'). */
export const breakdownToolTypes = (): string[] => uniqSorted(BREAKDOWN.map((e) => e.toolType))
/** The query_breakdown `platform` enum: platforms that serve at least one dimensional breakdown. */
export const breakdownPlatforms = (): string[] => uniqSorted(BREAKDOWN.map((e) => e.platform))
/** The query_breakdown `entityLevel` enum: every grain a dimensional breakdown is captured at. */
export const breakdownEntityLevels = (): string[] => uniqSorted(BREAKDOWN.flatMap((e) => e.entityLevels))
/** Total (platform, breakdown_type, entity_level) tuples this registry DECLARES — code-only, not live-DB. */
export const declaredTupleCount = (): number => REGISTRY.reduce((n, e) => n + e.entityLevels.length, 0)
/** Real metrics_daily breakdown_types + platforms behind a tool-facing type (geo → its 17 fine-grain types). */
export const resolveToolType = (toolType: string): BreakdownEntry[] => BREAKDOWN.filter((e) => e.toolType === toolType)
/** All platforms a tool-facing type is captured on (e.g. geo_country → shopify, meta, google). */
export const platformsForToolType = (toolType: string): string[] => uniqSorted(resolveToolType(toolType).map((e) => e.platform))
/** The one entry for a real (platform, breakdown_type), or undefined if not captured. */
export const entryFor = (platform: string, breakdownType: string): BreakdownEntry | undefined =>
  REGISTRY.find((e) => e.platform === platform && e.breakdownType === breakdownType)

// ── QUERY-LAYER derivations (src/lib/metrics-query.ts consumes these; its hand-maintained literals are deleted) ─
/** breakdown_type (REAL) → the platforms that serve it — the BREAKDOWN_PLATFORMS allowlist, registry-derived. */
export const breakdownPlatformsMap = (): Record<string, string[]> => {
  const m: Record<string, string[]> = {}
  for (const e of BREAKDOWN) (m[e.breakdownType] ||= []).push(e.platform)
  for (const k of Object.keys(m)) m[k] = uniqSorted(m[k])
  return m
}
/** SPEND_ZERO breakdown_types (per-action conversions, spend=0) = those whose default rank is conversions. */
export const spendZeroTypes = (): Set<string> => new Set(BREAKDOWN.filter((e) => e.rankBy === 'conversions').map((e) => e.breakdownType))
/** The tool-facing 'geo' collapse: (geoGrain, geoScope) → the REAL Google geo breakdown_type, or undefined. */
export const resolveGeo = (geoGrain: string, geoScope: string): string | undefined =>
  BREAKDOWN.find((e) => e.toolType === 'geo' && e.geoGrain === geoGrain && e.geoScope === geoScope)?.breakdownType
/** Valid geoGrain values on the collapsed 'geo' tool type (for the tool enum + description). */
export const geoGrains = (): string[] => uniqSorted(BREAKDOWN.filter((e) => e.toolType === 'geo' && e.geoGrain).map((e) => e.geoGrain as string))
/** Valid geoScope values: 'ad' = where you TARGETED, 'user' = where the person PHYSICALLY WAS (not interchangeable). */
export const geoScopes = (): string[] => uniqSorted(BREAKDOWN.filter((e) => e.toolType === 'geo' && e.geoScope).map((e) => e.geoScope as string))
// The 14 tool-facing types reachable at HEAD — the BYTE-IDENTICAL-protected set. Everything the registry declares
// beyond these is NEW reach → routed through the bounded top-N RPC (migration 039). This list is a FROZEN invariant,
// not an allowlist: it names the pre-2B contract so the query layer can keep those exact paths unchanged.
export const EXISTING_TOOL_TYPES: ReadonlySet<string> = new Set(['search_term', 'keyword', 'placement', 'age', 'gender', 'device', 'device_platform', 'hour', 'action_type', 'conversion_action', 'impression_share', 'video', 'geo_country', 'geo_region'])
